#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

# 字体颜色设置
Green="\033[32m"
Red="\033[31m"
GreenBG="\033[42;37m"
RedBG="\033[41;37m"
Font="\033[0m"

# IP 表定义
declare -a IP_TABLE=("137.220.171.40" "137.220.171.60") # Extend this list with your IPs

# 检查系统类型和版本
source '/etc/os-release'
OK="${Green}[OK]${Font}"
Error="${Red}[错误]${Font}"

# 判断是否为root用户
if [ 0 -ne $UID ]; then
    echo -e "${Error} ${RedBG} 当前用户不是root用户，请使用 'sudo -i' 切换到root用户后重新执行脚本 ${Font}"
    exit 1
fi

# 检查系统是否支持
check_system() {
    if [[ "${ID}" == "centos" && ${VERSION_ID} -ge 7 ]]; then
        INS="yum"
    elif [[ "${ID}" == "debian" && ${VERSION_ID} -ge 8 ]]; then
        INS="apt-get"
    elif [[ "${ID}" == "ubuntu" && $(echo "${VERSION_ID}" | cut -d '.' -f1) -ge 16 ]]; then
        INS="apt-get"
    else
        echo -e "${Error} ${RedBG} 当前系统 ${ID} ${VERSION_ID} 不支持，安装中断 ${Font}"
        exit 1
    fi
    $INS update -y
    $INS install -y curl
}

# 安装socks5
install_socks5() {
    wget -O /usr/local/bin/socks --no-check-certificate https://github.com/kangcwei/ss5/releases/download/ss5/socks
    chmod +x /usr/local/bin/socks

    systemctl daemon-reload
    systemctl enable sockd.service

    mkdir -p /etc/socks

    # 配置每个IP和端口
    port=4000
    for ip in "${IP_TABLE[@]}"; do
        systemctl start sockd.service
        echo -e "${OK} ${GreenBG} Socks5已安装完成 ${Font}"
        echo "${ip}:${port}"
        ((port++))
    done
}

check_system
install_socks5
